backend:
  name: github
  repo: elisealcala/portfolio
  branch: netlify-cms
  site_domain: elisealcala.com

local_backend: true

media_folder: static/assets
public_folder: /assets
# publish_mode: editorial_workflow

collections:
  - name: posts
    label: Posts
    folder: posts
    path: '{{slug}}/index'
    create: true
    fields:
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: date, label: Date, widget: datetime }
      - { name: published, label: Published, widget: 'boolean', default: false }
      - { name: body, label: Body, widget: markdown }
