backend:
  name: github
  repo: elisealcala/portfolio
  branch: master
  site_domain: elisealcala.com

local_backend: true

media_folder: static/assets
public_folder: /assets
publish_mode: editorial_workflow

collections:
  - name: posts
    label: Posts
    folder: posts
    path: '{{slug}}/index'
    create: true
    fields:
      - { name: title, label: Title, required: true }
      - { name: tags, label: Tags, widget: list }
      - { name: description, label: Description, required: true }
      - { name: date, label: Date, widget: datetime, required: true }
      - { name: published, label: Published, widget: 'boolean', default: false }
      - { name: body, label: Body, widget: markdown, required: true }
