backend:
  name: github
  repo: elisealcala/portfolio
  branch: netlify-cms
  site_domain: elisealcala.com

media_folder: static/assets
public_folder: /assets
publish_mode: editorial_workflow

collections:
  - name: posts
    label: Posts
    folder: posts/{{slug}}
    create: true
    fields:
      - { name: path, label: Path }
      - { name: description, label: Description }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
